/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as StatementsRouteImport } from './routes/statements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/credits' | '/expenses' | '/forecast' | '/goals' | '/statements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/credits' | '/expenses' | '/forecast' | '/goals' | '/statements'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/expenses'
    | '/forecast'
    | '/goals'
    | '/statements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  ExpensesRoute: typeof ExpensesRoute
  ForecastRoute: typeof ForecastRoute
  GoalsRoute: typeof GoalsRoute
  StatementsRoute: typeof StatementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  ExpensesRoute: ExpensesRoute,
  ForecastRoute: ForecastRoute,
  GoalsRoute: GoalsRoute,
  StatementsRoute: StatementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
